obj-m := rockchip-vdec.o

rockchip-vdec-y := \
	rkvdec.o \
	rkvdec-cabac.o \
	rkvdec-link.o \
	rkvdec-h264.o \
	rkvdec-h264-common.o \
	rkvdec-hevc.o \
	rkvdec-hevc-common.o \
	rkvdec-rcb.o \
	rkvdec-vdpu381-h264.o \
	rkvdec-vdpu381-hevc.o \
	rkvdec-vdpu383-h264.o \
	rkvdec-vdpu383-hevc.o \
	rkvdec-vdpu383-av1.o \
	rkvdec-vdpu383-vp9.o \
	rkvdec-vp9.o
